=== Enigma-Game/Enigma/data/schemas/level.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema' targetNamespace="http://enigma-game.org/schema/level/1" xmlns:el="http://enigma-game.org/schema/level/1" elementFormDefault="qualified" attributeFormDefault="qualified" version="0.5" xml:lang="en">
  <xs:annotation>
    <xs:documentation>
      XML schema definitions for Enigma levels
      Copyright Â© 2006,2007,2008,2009,2010 Ronald Lamprecht

      This program is free software; you can redistribute it and/or
      modify it under the terms of the GNU General Public License
      as published by the Free Software Foundation; either version 2
      of the License, or (at your option) any later version.

      This program is distributed in the hope that it will be useful,
      but WITHOUT ANY WARRANTY; without even the implied warranty of
      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
      GNU General Public License for more details.

      You should have received a copy of the GNU General Public License along
      with this program; if not, write to the Free Software Foundation, Inc.,
      51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
    </xs:documentation>
  </xs:annotation>
  <xs:element name="level">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="protected" minOccurs="1" maxOccurs="1">
          <xs:annotation>
            <xs:documentation>
              The protected section is reserved for data from the level author.
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="info" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="identity" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="title" type="xs:string" use="required"/>
                        <xs:attribute name="subtitle" type="xs:string" use="optional"/>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element> <!-- identity -->
                    <xs:element name="version" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="score" type="xs:positiveInteger" use="required"/>
                        <xs:attribute name="release" type="xs:positiveInteger" use="required"/>
                        <xs:attribute name="revision" use="required">
                          <xs:simpleType>
                            <xs:union memberTypes="xs:unsignedShort el:revisionType"/>
                          </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="status" type="el:statusType" use="required"/>
                      </xs:complexType>
                    </xs:element> <!-- version -->
                    <xs:element name="author" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="name" type="xs:string" default="anonymous" use="optional"/>
                        <xs:attribute name="email" type="xs:anyURI" use="optional"/>
                        <xs:attribute name="homepage" type="xs:anyURI" use="optional"/>
                      </xs:complexType>
                    </xs:element> <!-- author -->
                    <xs:element name="copyright" minOccurs="1" maxOccurs="1" type="xs:string"/>
                    <xs:element name="license" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="type" type="xs:string" use="required"/>
                            <xs:attribute name="open" type="xs:boolean" use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element> <!-- license -->
                    <xs:element name="compatibility" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="dependency" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="path" type="xs:string" use="required"/>
                              <xs:attribute name="id" type="xs:string" use="required"/>
                              <xs:attribute name="release" type="xs:unsignedShort" use="required"/>
                              <xs:attribute name="preload" type="xs:boolean" use="required"/>
                              <xs:attribute name="url" type="xs:anyURI" use="optional"/>
                            </xs:complexType>
                          </xs:element> <!-- dependency -->
                          <xs:element name="externaldata" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="path" type="xs:string" use="optional"/>
                              <xs:attribute name="url" type="xs:anyURI" use="optional"/>
                            </xs:complexType>
                          </xs:element> <!-- externaldata -->
                          <xs:element name="editor" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                              <xs:attribute name="name" type="xs:string" use="required"/>
                              <xs:attribute name="version" type="xs:string" use="required"/>
                            </xs:complexType>
                          </xs:element> <!-- editor -->
                          <xs:element name="extensions" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:any namespace="##targetNamespace" minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element> <!-- extensions -->
                        </xs:sequence>
                        <xs:attribute name="enigma" type="xs:float" use="required"/>
                        <xs:attribute name="engine" type="xs:string" use="optional" default="enigma"/>
                      </xs:complexType>
                    </xs:element> <!-- compatibility -->
                    <xs:element name="modes" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="easy" type="xs:boolean" use="required"/>
                        <xs:attribute name="single" type="xs:boolean" use="required"/>
                        <xs:attribute name="network" type="xs:boolean" use="required"/>
                        <xs:attribute name="control" type="el:controlType" use="optional" default="force"/>
                        <xs:attribute name="scoreunit" type="el:scoreunitType" use="optional" default="duration"/>
                        <xs:attribute name="scoretarget" type="xs:string" use="optional" default="time"/>
                      </xs:complexType>
                    </xs:element> <!-- modes -->
                    <xs:element name="comments" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="credits" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:token">
                                  <xs:attribute name="showinfo" type="xs:boolean" use="optional" default="false"/>
                                  <xs:attribute name="showstart" type="xs:boolean" use="optional" default="false"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element> <!-- credits -->
                          <xs:element name="dedication" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:token">
                                  <xs:attribute name="showinfo" type="xs:boolean" use="optional" default="false"/>
                                  <xs:attribute name="showstart" type="xs:boolean" use="optional" default="false"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element> <!-- dedication -->
                          <xs:element name="code" minOccurs="0" maxOccurs="1" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element> <!-- comments -->
                    <xs:element name="update" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="url" type="xs:anyURI" use="required"/>
                      </xs:complexType>
                    </xs:element> <!-- update -->
                    <xs:element name="upgrade" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="url" type="xs:anyURI" use="required"/>
                        <xs:attribute name="release" type="xs:unsignedShort" use="required"/>
                      </xs:complexType>
                    </xs:element> <!-- upgrade -->
                    <xs:element name="preview" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:anyAttribute namespace="##targetNamespace" processContents="skip"/>
                      </xs:complexType>
                    </xs:element> <!-- preview -->
                    <xs:element name="score" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="easy" type="el:scoreType" use="required"/>
                        <xs:attribute name="difficult" type="el:scoreType" use="required"/> 
                      </xs:complexType>
                    </xs:element> <!-- score -->
                    
                    <xs:any namespace="##targetNamespace" minOccurs="0" maxOccurs="unbounded" processContents="skip"/>

                  </xs:sequence>
                  <xs:attribute name="type" type="el:fileType" use="required"/>
                  <xs:attribute name="quantity" type="xs:positiveInteger" use="optional" default="1"/>
                </xs:complexType>
              </xs:element> <!-- info -->
              
              <xs:element name="elements" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:any namespace="##targetNamespace" minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element> <!-- elements -->
              
              <xs:element name="luamain" minOccurs="0" maxOccurs="1" type="xs:string"/>
              
              <xs:any namespace="##other" minOccurs="0" maxOccurs="1" processContents="skip">
                <xs:annotation>
                  <xs:documentation>
                    Any external level editor is free to include an element of its own
                    namespace for storage of any extensions. This element is ignored by
                    enigma. The editor is free to supply an additional schema for its 
                    element definitions.
                  </xs:documentation>
                </xs:annotation>
              </xs:any>
              
              <xs:element name="i18n" minOccurs="1" maxOccurs="1" >
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="string" minOccurs="0" maxOccurs="unbounded" >
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="english" minOccurs="1" maxOccurs="1">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:normalizedString">
                                  <xs:attribute name="translate" type="xs:boolean" default="true"/>
                                  <xs:attribute name="comment" type="xs:string" use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element> <!-- english -->
                          <xs:element name="translation" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:normalizedString">
                                  <xs:attribute name="lang" type="xs:language" use="required"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element> <!-- translation -->
                        </xs:sequence>
                        <xs:attribute name="key" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element> <!-- string -->
                  </xs:sequence>
                </xs:complexType>
              </xs:element> <!-- i18n -->
              
              <xs:any namespace="##targetNamespace" minOccurs="0" maxOccurs="unbounded" processContents="skip"/>

            </xs:sequence>
            <xs:anyAttribute namespace="##targetNamespace" processContents="skip"/>
          </xs:complexType>
        </xs:element> <!-- protected -->
        
        <xs:element name="public" minOccurs="0" maxOccurs="1">
          <xs:annotation>
            <xs:documentation>
              The pubic section for not validated additions by others. All info
              in public is handeled with care by enigma. Translations will be
              suggested to the official translators and only be used if confirmed
              or missing in the translators translations.
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="i18n" minOccurs="0" maxOccurs="1" >
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="string" minOccurs="0" maxOccurs="unbounded" >
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="translation" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:normalizedString">
                                  <xs:attribute name="lang" type="xs:language" use="required"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element> <!-- translation -->
                        </xs:sequence>
                        <xs:attribute name="key" type="xs:ID" use="required">
                          <xs:annotation>
                            <xs:documentation>
                              Usage of type xs:ID instead of xs:string is required by evaluation
                              XSLT stylesheets. 
                              It limits the public/i18n/strings to key-identifier usage instead
                              of original complete english string as key usage. But this is not
                              too bad, because it reduces errors due to changed english strings 
                              in the protected area.
                              The ID type guarantees us uniqueness within public/i18n and allows
                              stylesheets and programs to use XPaths to crossover from a 
                              protected/i18n/string to the corresponding public/i18n/string.
                            </xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                      </xs:complexType>
                    </xs:element> <!-- string -->
                  </xs:sequence>
                </xs:complexType>
              </xs:element> <!-- i18n -->
              <xs:element name="upgrade" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:attribute name="url" type="xs:anyURI" use="required"/>
                  <xs:attribute name="release" type="xs:unsignedShort" use="required"/>
                </xs:complexType>
              </xs:element> <!-- upgrade -->
              <xs:element name="extensions" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:any namespace="##targetNamespace" minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element> <!-- extensions -->
            </xs:sequence>
          </xs:complexType>
        </xs:element> <!-- public -->
      </xs:sequence>
    </xs:complexType>
    
    <xs:key name="stringkey">
      <xs:selector xpath="el:protected/el:i18n/el:string"/>
      <xs:field xpath="@el:key"/>
    </xs:key>
    <xs:keyref name="translationkey" refer="el:stringkey">
      <xs:selector xpath="el:public/el:i18n/el:string"/>
      <xs:field xpath="@el:key"/>
    </xs:keyref>
  </xs:element>
  
  <xs:simpleType name="fileType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="level"/>
      <xs:enumeration value="multilevel"/>
      <xs:enumeration value="library"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="revisionType">
    <xs:restriction base="xs:string">
      <xs:pattern value="$Revision[:]?[ ]*[\d]*[ ]*$"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="statusType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="released"/>
      <xs:enumeration value="stable"/>
      <xs:enumeration value="test"/>
      <xs:enumeration value="experimental"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="controlType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="force"/>
      <xs:enumeration value="balance"/>
      <xs:enumeration value="key"/>
      <xs:enumeration value="other"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="scoreunitType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="duration"/>
      <xs:enumeration value="number"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="scoreType">
    <xs:restriction base="xs:string">
      <xs:pattern value="-|([ \d]?\d:[012345]\d)|(\d)+"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== Enigma-Game/Enigma/data/levels/enigma_i/jc03_1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<el:level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://enigma-game.org/schema/level/1 level.xsd" xmlns:el="http://enigma-game.org/schema/level/1">
  <el:protected>
    <el:info el:type="level">
      <el:identity el:title="Why So Slow?" el:subtitle="" el:id="jc03"/>
      <el:version el:score="1" el:release="1" el:revision="0" el:status="released"/>
      <el:author  el:name="Jens-Christian Korth" el:email="" el:homepage=""/>
      <el:copyright>Copyright Â© Jens-Christian Korth</el:copyright>
      <el:license el:type="Donated to Enigma under the projects license" el:open="true"/>
      <el:compatibility el:enigma="0.92">
      </el:compatibility>
      <el:modes el:easy="false" el:single="true" el:network="false"/>
      <el:comments>
        <el:code>Lua 5.1 and XML converted by Leveladministrators</el:code>
      </el:comments>
      <el:score el:easy="-" el:difficult="-"/>
    </el:info>
    <el:luamain><![CDATA[
Force = 40
ForceX = 0
ForceY = 0

function SetForce(x,y)
   enigma.AddConstantForce(x, y)
   ForceX = x
   ForceY = y
end

function swT()
   SetForce(ForceX, Force)
end

function swB()
   SetForce(ForceX, -Force)
end

function swL()
   SetForce(Force, ForceY)
end

function swR()
   SetForce(-Force, ForceY)
end

create_world(20, 13) 
oxyd_default_flavor = "d"
draw_border("st-rock5")
fill_floor("fl-bluegray")
set_floor("fl-abyss",  1,  1)
set_floor("fl-abyss", 18,  1)
set_floor("fl-abyss",  1, 11)
set_floor("fl-abyss", 18, 11)

for i = 2, 17 do
   set_item("it-trigger",  i,  1, {action="callback", target="swT"})
   set_item("it-trigger",  i, 11, {action="callback", target="swB"})
end

for i = 2, 10 do
   set_item("it-trigger",  1,  i, {action="callback", target="swL"})
   set_item("it-trigger", 18,  i, {action="callback", target="swR"})
end

oxyd( 2, 0)
oxyd( 7, 0)
oxyd(12, 0)
oxyd(17, 0)
oxyd( 2,12)
oxyd( 7,12)
oxyd(12,12)
oxyd(17,12)
oxyd( 0, 3)
oxyd( 0, 9)
oxyd(19, 3)
oxyd(19, 9)
oxyd_shuffle() 

set_actor("ac-blackball", 10,6.5)

SetForce(2*Force, -2*Force)
    ]]></el:luamain>
    <el:i18n>
      <el:string el:key="title">
        <el:english el:translate="false"/>
      </el:string>
    </el:i18n>
  </el:protected>
</el:level>

=== Enigma-Game/Enigma/data/levels/enigma_oxydextra/oxe17_2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<el:level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://enigma-game.org/schema/level/1 level.xsd" xmlns:el="http://enigma-game.org/schema/level/1">
  <el:protected>
    <el:info el:type="level">
      <el:identity el:title="Invisible Path" el:subtitle="Oxyd Extra 17" el:id="oxe17"/>
      <el:version el:score="1" el:release="2" el:revision="2" el:status="released"/>
      <el:author el:name="Raoul Bourquin" el:email=""/>
      <el:copyright>Copyright Â© 2013 Raoul Bourquin</el:copyright>
      <el:license el:type="GPL v2.0 or above" el:open="true"/>
      <el:compatibility el:engine="oxyd.extra" el:enigma="1.30"/>
      <el:modes el:easy="false" el:single="true" el:network="false"/>
      <el:score el:easy="-" el:difficult="-"/>
    </el:info>
    <el:luamain><![CDATA[
ti["  "] = {"fl_gray"}
ti[". "] = {"fl_ivory"}
ti["- "] = {"fl_dark"}
ti[" #"] = {"st_invisible"}
ti[" O"] = {"st_oxyd", flavor="a"}
ti[" @"] = {"#ac_marble_black"}

wo(res.composer(ti), "  ", {
    " #.# #.# #.# #.# #.# #.# #.# #.# #.# #.#",
    ".#- . - . - . - .#- . -#.#-#. - . - . -#",
    " #.# #.O #.# #.   .#  .   .   .# O.#  .#",
    ".#- . - . - . -#. - . -#.#-#. - . -#. -#",
    " #.  #.# #.  #.# #.#  .   .  #.  #.   .#",
    ".#- .#-O.#- . - . -#. -#. -#.#-#.O- .#-#",
    " #.  #.   .  #.  #.  @.#  .  #.# #.#  .#",
    ".#- . -#.#- .#- .#-#. -#.#- . - . -#. -#",
    " #.  #.O #.  #.   .   .#  .#  .# O.#  .#",
    ".#- . - .#- .#- .#-#.#-#. - . - . - . -#",
    " #.# #.# #.# #.# #.# #.# #.# #.# #.# #.#"})

wo:shuffleOxyd()
 ]]></el:luamain>
    <el:i18n>
      <el:string el:key="title">
        <el:english el:translate="false"/>
      </el:string>
    </el:i18n>
  </el:protected>
</el:level>

=== Enigma-Game/Enigma/data/levels/enigma_viii/devnull28_1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<el:level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://enigma-game.org/schema/level/1 level.xsd" xmlns:el="http://enigma-game.org/schema/level/1">
  <el:protected>
    <el:info el:type="level">
      <el:identity el:title="Two Is A Company IV" el:subtitle="" el:id="devnull28"/>
      <el:version el:score="1" el:release="1" el:revision="1" el:status="released"/>
      <el:author  el:name="/dev/null" el:email="" el:homepage=""/>
      <el:copyright>Copyright Â© 2008 dev0</el:copyright>
      <el:license el:type="GPL v2.0 or above" el:open="true"/>
      <el:compatibility el:enigma="1.10"/>
      <el:modes el:easy="false" el:single="true" el:network="true"/>
      <el:score el:easy="-" el:difficult="6:54"/>
    </el:info>
    <el:luamain><![CDATA[
wo["ConserveLevel"] = false
wo["ProvideExtralifes"] = false

ti["#"] = {"st_redrock"}
ti[" "] = {"fl_concrete"}
ti["~"] = {"fl_water"}
ti["R"] = {"st_box_rock"}
ti["box"] = {"st_box_rock", "box%%"}
ti["pull"] = {"st_pull", "pull%%"}
ti["B"] = {"st_box_rock", "black"}
ti["W"] = {"st_box_rock", "white"}
ti["o"] = {"st_oxyd_a", name = "left#", static = true}
ti["O"] = {"st_oxyd_a", name = "right#", static = true}
ti["@"] = {"#ac_marble_black", essential = INDISPENSIBLE}
ti["*"] = {"#ac_marble_white", essential = INDISPENSIBLE}

local resolver = res.autotile(ti, {"1", "2", "box"}, {"3", "4", "pull"})
wo(resolver, " ", {
    "####################",
    "#          ~~~~~# @#",
    "# ###      ~~~~~#32#",
    "#   #~~~~~~~~~~## ~#",
    "#   #~~~~~~~~~~#   #",
    "###~#~~~~BO~~~~# # #",
    "#   #~~~~oO~~~~#   #",
    "# R #~~~~oW~~~~###~#",
    "# ~ #~~~~~~~~~~# RR#",
    "#~###~~~~~~~~~~#   #",
    "#41 #~~~~      #####",
    "#*  #~~~~          #",
    "####################"})

wo:shuffleOxyd({"left#*", max = 0}, {"right#*", max = 0})
wo:add({"ot_wire", anchor1 = "box%1", anchor2 = "pull%1"})
wo:add({"ot_wire", anchor1 = "pull%1", anchor2 = "black"})
wo:add({"ot_wire", anchor1 = "box%2", anchor2 = "pull%2"})
wo:add({"ot_wire", anchor1 = "pull%2", anchor2 = "white"})
 ]]></el:luamain>
    <el:i18n>
      <el:string el:key="title">
        <el:english el:translate="false"/>
      </el:string>
    </el:i18n>
  </el:protected>
</el:level>

=== Enigma-Game/Enigma/data/levels/stable/andreas28.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<el:level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://enigma-game.org/schema/level/1 level.xsd" xmlns:el="http://enigma-game.org/schema/level/1">
  <el:protected>
    <el:info el:type="level">
      <el:identity el:title="Dancing on Light Beams" el:subtitle="" el:id="stable/andreas28"/>
      <el:version el:score="1" el:release="1" el:revision="0" el:status="released"/>
      <el:author  el:name="Andreas Lochmann" el:email="" el:homepage=""/>
      <el:copyright>Copyright Â© 2006 Andreas Lochmann</el:copyright>
      <el:license el:type="GPL v2.0 or above" el:open="true"/>
      <el:compatibility el:enigma="0.92">
      </el:compatibility>
      <el:modes el:easy="false" el:single="true" el:network="false"/>
      <el:comments>
        <el:code>Lua 5.1 and XML converted by Leveladministrators</el:code>
      </el:comments>
      <el:score el:easy="-" el:difficult="-"/>
    </el:info>
    <el:luamain><![CDATA[
-- Created with the help of BBE 1.05

Require("levels/lib/ant.lua")

levelh=13
levelw=20
enigma.FlatForce=30
enigma.SlopeForce=30
enigma.ElectricForce=30

function file_oxyd(x,y,f)
    oxyd_default_flavor=f
    oxyd(x,y)
end

function ac_blackball(x,y)
  set_actor("ac-blackball",x+0.5,y+0.5,{player=0,mouseforce=1.7})
end

function set_laser(x,y,s)
  set_stone(s, x, y, {on = TRUE})
end

cells={}
items={}
actors={}
stones={}
actors[" "]=cell{}
stones[" "]=cell{}
cells[" "]=cell{}
items[" "]=cell{}

cells["!"]=cell{floor="fl-stone"}

stones["!"]=cell{stone="st-rock8"}
stones["O"]=cell{parent={{file_oxyd,"b"}}}
stones["S"]=cell{parent={{set_laser, "st-laser-s"}}}
stones["N"]=cell{parent={{set_laser, "st-laser-n"}}}
stones["E"]=cell{parent={{set_laser, "st-laser-e"}}}
stones["W"]=cell{parent={{set_laser, "st-laser-w"}}}
stones["B"]=cell{stone="st-polarswitch"}
stones["L"]=cell{stone="st-lightpassenger"}
stones["M"]=cell{stone="st-stoneimpulse_movable"}

actors["!"]=cell{parent={{ac_blackball}}}

level={"!!!!!!!!!!!!!!!!!!!!",
       "!!!!!!!!!!!!!!!!!!!!",
       "!!!!!!!!!!!!!!!!!!!!",
       "!!!!!!!!!!!!!!!!!!!!",
       "!!!!!!!!!!!!!!!!!!!!",
       "!!!!!!!!!!!!!!!!!!!!",
       "!!!!!!!!!!!!!!!!!!!!",
       "!!!!!!!!!!!!!!!!!!!!",
       "!!!!!!!!!!!!!!!!!!!!",
       "!!!!!!!!!!!!!!!!!!!!",
       "!!!!!!!!!!!!!!!!!!!!",
       "!!!!!!!!!!!!!!!!!!!!",
       "!!!!!!!!!!!!!!!!!!!!"}
acmap={"                    ",
       "                    ",
       "                    ",
       "                    ",
       "       !            ",
       "                    ",
       "                    ",
       "                    ",
       "                    ",
       "                    ",
       "                    ",
       "                    ",
       "                    "}
itmap={"                    ",
       "                    ",
       "                    ",
       "                    ",
       "                    ",
       "                    ",
       "                    ",
       "                    ",
       "                    ",
       "                    ",
       "                    ",
       "                    ",
       "                    "}
stmap={"!!S!!S!!!!!!!!!!!!!!",
       "! B  B             !",
       "!          BW  S S !",
       "!  S B         B B !",
       "!  B L    EB       !",
       "EB        B    B   !",
       "!            B    BW",
       "!    B  B       BBW!",
       "!EB           B    !",
       "!       B   B      !",
       "!!!!!!!!N!!!N!!!!  !",
       "!M M M M M M M M  BW",
       "!!!!!!!!!!OOOOOO!!!!"}

create_world_by_map(level)
draw_map(0,0,stmap,stones)
draw_map(0,0,itmap,items)
draw_map(0,0,acmap,actors)

oxyd_shuffle()
    ]]></el:luamain>
    <el:i18n>
      <el:string el:key="title">
        <el:english el:translate="false"/>
      </el:string>
    </el:i18n>
  </el:protected>
</el:level>
